#!/bin/bash

VERSION="1.1.0"

XAMPP="/Applications/XAMPP/xamppfiles/xampp"
MYSQLD="/Applications/XAMPP/xamppfiles/sbin/mysqld"
HTTPD="/Applications/XAMPP/xamppfiles/bin/httpd"

GREEN="\033[32m"
RED="\033[31m"
YELLOW="\033[33m"
CYAN="\033[36m"
BOLD="\033[1m"
RESET="\033[0m"


spinner() {

    local pid=$1
    local message=$2

    local frames=("⠋" "⠙" "⠸" "⠴" "⠦" "⠇")
    local i=0

    while kill -0 "$pid" 2>/dev/null; do
        printf "\r%s %s" "$message" "${frames[$i]}"
        i=$(( (i+1) % 6 ))
        sleep 0.1
    done

    printf "\r%s ${GREEN}✓${RESET}\n" "$message"
}


run() {

    local message="$1"
    shift

    sudo -v

    "$@" >/tmp/xampp-cli.log 2>&1 &
    local pid=$!

    spinner "$pid" "$message"

    wait "$pid"

    if [ $? -ne 0 ]; then
        echo -e "${RED}✗ Failed${RESET}"
        cat /tmp/xampp-cli.log
        return 1
    fi
}


mysql_running() {

    sudo "$XAMPP" status 2>/dev/null | grep -qi "MySQL is running"

}


apache_running() {

    sudo "$XAMPP" status 2>/dev/null | grep -qi "Apache is running"

}


start_mysql() {

    if mysql_running; then
        echo -e "MySQL: ${YELLOW}already running${RESET}"
    else
        run "Starting MySQL..." sudo "$XAMPP" startmysql
    fi
}


stop_mysql() {

    if mysql_running; then

        run "Stopping MySQL..." sudo "$XAMPP" stopmysql

        sleep 2

        if mysql_running; then
            echo -e "${YELLOW}Force stopping MySQL...${RESET}"

            PID=$(pgrep -f "$MYSQLD")

            if [ -n "$PID" ]; then
                sudo kill -9 "$PID"
            fi
        fi

        echo -e "MySQL: ${GREEN}stopped${RESET}"

    else
        echo -e "MySQL: ${YELLOW}already stopped${RESET}"
    fi
}


start_apache() {

    if apache_running; then
        echo -e "Apache: ${YELLOW}already running${RESET}"
    else
        run "Starting Apache..." sudo "$XAMPP" startapache
    fi
}


stop_apache() {

    if apache_running; then
        run "Stopping Apache..." sudo "$XAMPP" stopapache
        echo -e "Apache: ${GREEN}stopped${RESET}"
    else
        echo -e "Apache: ${YELLOW}already stopped${RESET}"
    fi
}


status() {

    echo ""
    echo -e "${BOLD}XAMPP Status${RESET}"
    echo "------------"

    if mysql_running; then
        echo -e "MySQL:  ${GREEN}running${RESET}"
    else
        echo -e "MySQL:  ${RED}stopped${RESET}"
    fi


    if apache_running; then
        echo -e "Apache: ${GREEN}running${RESET}"
    else
        echo -e "Apache: ${RED}stopped${RESET}"
    fi

    echo ""

}


start_all() {

    echo ""
    echo -e "${CYAN}Starting XAMPP...${RESET}"
    echo ""

    start_mysql
    start_apache

    echo ""
    echo -e "${GREEN}XAMPP is ready.${RESET}"
    echo ""

}


stop_all() {

    echo ""
    echo -e "${CYAN}Stopping XAMPP...${RESET}"
    echo ""

    stop_apache
    stop_mysql

    echo ""
    echo -e "${GREEN}XAMPP stopped.${RESET}"
    echo ""

}


help() {

    echo ""
    echo -e "${BOLD}XAMPP CLI v$VERSION${RESET}"
    echo ""
    echo "Usage:"
    echo ""
    echo "  xampp start"
    echo "  xampp stop"
    echo "  xampp restart"
    echo ""
    echo "  xampp mysql start"
    echo "  xampp mysql stop"
    echo ""
    echo "  xampp apache start"
    echo "  xampp apache stop"
    echo ""
    echo "  xampp status"
    echo "  xampp help"
    echo ""

}


case "$1:$2" in


start:)
    start_all
;;


stop:)
    stop_all
;;


restart:)
    stop_all
    sleep 2
    start_all
;;


mysql:start)
    start_mysql
;;


mysql:stop)
    stop_mysql
;;


apache:start)
    start_apache
;;


apache:stop)
    stop_apache
;;


status:)
    status
;;


help:)
    help
;;


*)
    help
;;

esac